service:
  name: serverless-nodejs-ts

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-southeast-2

functions:
  hello:
    handler: src/controllers/index.hello
    events:
      - http:
          method: get
          path: /
